# Wrangler configuration for SelfHostLLM GPU Calculator Worker
name = "selfhostllm"
account_id = "aca6c76689cfd2a4f791b6e38bf0444d"
main = "worker.js"
compatibility_date = "2024-01-01"

# Worker route (update with your domain)
# route = "selfhostllm.org/*"
# or use workers.dev subdomain
workers_dev = true

# Static assets configuration
[site]
bucket = "./"

# Development configuration
[dev]
port = 8080
local_protocol = "http"